job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    git('LocalGit')
    scm {
        git("https://github.com/thisismanikandan/Jenkins_Upgradev3.git", 'main')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean validate install package', 'maven-samples/single-module/pom.xml')
    }
    publishers {
        //archives the jar files generated
        archiveArtifacts '**/*.jar'
    }
}
